version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./:/app # ホストの.（ルートディレクトリ）をコンテナの/appディレクトリにマッピング
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=database
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app # ホストの./frontedディレクトリをコンテナの/appディレクトリにマッピング
  database:
    build: ./database
    command: --secure-file-priv=""
    volumes:
      - db_data:/var/lib/mysql
      - .database:/var/lib/mysql-files
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
volumes:
  db_data: