version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./:/app # ホストの.（ルートディレクトリ）をコンテナの/appディレクトリにマッピング
      - ./backend/uploads:/app/uploads # 新しく追加した行
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
      - HOME_URL=${HOME_URL}
      - FLASK_ENV = ${FLASK_ENV}
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app # ホストの./frontedディレクトリをコンテナの/appディレクトリにマッピング
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - ANOTHER_ENV_VAR=value
  database:
    build: ./database
    command: --secure-file-priv=""
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
volumes:
  db_data: