version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app  # ホストの./backendディレクトリをコンテナの/appディレクトリにマッピング
  fronted:
    build: ./fronted
    ports:
      - 3000:3000
    volumes:
      - ./fronted:/app  # ホストの./frontedディレクトリをコンテナの/appディレクトリにマッピング
  database:
    build: ./database
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: