# ベースとするDockerイメージの指定
FROM mysql:8.0

# CSVファイルとSQLスクリプトをdocker containerにcopy
COPY ./GAMSampleData_2_masked.csv /docker-entrypoint-initdb.d/GAMSampleData_2_masked.csv
COPY ./GAMSampleData.sql /docker-entrypoint-initdb.d/GAMSampleData.sql

# databaseディレクトリ配下でdatabaseを作成
# DB containerの作成もここで行う
# ローカルの情報(csv)をコンテナ内に移す方法は調べればありそう
# DB作る table作る insertする