# ベースとするDockerイメージの指定
FROM mysql:8.0

# CSVファイルとSQLスクリプトをdocker containerにcopy
COPY ./GAMSampleData_1.csv /docker-entrypoint-initdb.d/GAMSampleData_1.csv
COPY ./GAMSampleData_1.sql /docker-entrypoint-initdb.d/GAMSampleData_1.sql

# databaseディレクトリ配下でdatabaseを作成
# DB containerの作成もここで行う
# ローカルの情報(csv)をコンテナ内に移す方法は調べればありそう
# DB作る table作る insertする